# Generated by Django 4.0.6 on 2022-09-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryinfo',
            name='average_price_to_sales',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='industryinfo',
            name='industry_identifier',
            field=models.TextField(default='test'),
        ),
        migrations.AlterField(
            model_name='industryinfo',
            name='average_revenue',
            field=models.FloatField(default=0.6),
        ),
    ]
