# Generated by Django 4.0.6 on 2022-09-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_industryinfo_average_price_to_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryinfo',
            name='average_price_to_sales',
            field=models.FloatField(default=0.59),
        ),
    ]
