# Generated by Django 4.0.6 on 2022-09-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_industryinfo_average_price_to_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryinfo',
            name='industry_identifier',
            field=models.TextField(default='industry'),
        ),
    ]
