# Generated by Django 4.0.6 on 2022-09-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_industryinfo_industry_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryinfo',
            name='average_price_to_sales',
        ),
        migrations.RemoveField(
            model_name='industryinfo',
            name='average_revenue',
        ),
        migrations.RemoveField(
            model_name='industryinfo',
            name='industry_identifier',
        ),
        migrations.AddField(
            model_name='industryinfo',
            name='avg_pe',
            field=models.FloatField(default=69.69),
        ),
        migrations.AddField(
            model_name='industryinfo',
            name='name',
            field=models.TextField(default='default'),
        ),
    ]
