# Generated by Django 4.0.6 on 2022-09-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_industryinfo_average_price_to_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryinfo',
            name='avg_eps',
            field=models.FloatField(default=69.69),
        ),
        migrations.AddField(
            model_name='industryinfo',
            name='avg_fwdpe',
            field=models.FloatField(default=69.69),
        ),
        migrations.AddField(
            model_name='industryinfo',
            name='avg_pb',
            field=models.FloatField(default=69.69),
        ),
        migrations.AddField(
            model_name='industryinfo',
            name='avg_ps',
            field=models.FloatField(default=69.69),
        ),
    ]
