# Generated by Django 4.0.6 on 2022-09-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_industryinfo_avg_eps_industryinfo_avg_fwdpe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField(default='default')),
                ('industry', models.TextField(default='default')),
                ('sector', models.TextField(default='default')),
                ('company_name', models.TextField(default='default')),
                ('beta', models.FloatField(default=69.69)),
                ('pb', models.FloatField(default=69.69)),
                ('ps', models.FloatField(default=69.69)),
                ('pe', models.FloatField(default=69.69)),
                ('fwdpe', models.FloatField(default=69.69)),
                ('eps', models.FloatField(default=69.69)),
                ('mkt_cap_short', models.TextField(default='default')),
                ('mkt_cap', models.FloatField(default=69.69)),
                ('revenue_short', models.TextField(default='default')),
                ('revenue', models.FloatField(default=69.69)),
                ('profit_short', models.TextField(default='default')),
                ('profit', models.FloatField(default=69.69)),
                ('profit_margin', models.TextField(default='default')),
                ('profit_margin_float', models.FloatField(default=69.69)),
                ('rev_growth', models.TextField(default='default')),
                ('rev_growth_float', models.FloatField(default=69.69)),
                ('avg_volume', models.FloatField(default=69.69)),
                ('shares_float', models.FloatField(default=69.69)),
                ('short_float', models.TextField(default='default')),
            ],
        ),
    ]
