# Generated by Django 4.0.6 on 2022-09-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_stockinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryinfo',
            name='avg_mkt_cap',
            field=models.FloatField(default=69.69),
        ),
        migrations.AddField(
            model_name='industryinfo',
            name='ind_size',
            field=models.FloatField(default=69.69),
        ),
    ]
