# Generated by Django 4.0.6 on 2022-09-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_ticker_stockinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Ticker')),
                ('industry', models.TextField(default='Industry')),
                ('sector', models.TextField(default='Sector')),
            ],
        ),
    ]
