# Generated by Django 4.0.6 on 2022-09-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_stocktest_beta_stocktest_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktest',
            name='eps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='fwdpe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='pb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='pe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='ps',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stocktest',
            name='beta',
            field=models.FloatField(default=0),
        ),
    ]
