# Generated by Django 4.0.6 on 2022-09-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_stocktest_eps_stocktest_fwdpe_stocktest_pb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktest',
            name='mkt_cap',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='mkt_cap_short',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='revenue_short',
            field=models.TextField(default='default'),
        ),
    ]
