# Generated by Django 4.0.6 on 2022-09-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_stocktest_mkt_cap_stocktest_mkt_cap_short_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktest',
            name='avg_volume',
            field=models.TextField(default='Avg Volume'),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='profit_margin',
            field=models.TextField(default='Profit Margin'),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='profit_margin_float',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='profit_short',
            field=models.TextField(default='Profit Short'),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='rev_growth',
            field=models.TextField(default='Rev Growth'),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='rev_growth_float',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='shares_float',
            field=models.TextField(default='Shares Float'),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='short_float',
            field=models.TextField(default='Short Float'),
        ),
        migrations.AlterField(
            model_name='stocktest',
            name='mkt_cap_short',
            field=models.TextField(default='Market Cap Short'),
        ),
        migrations.AlterField(
            model_name='stocktest',
            name='revenue_short',
            field=models.TextField(default='Revenue Short'),
        ),
    ]
