# Generated by Django 4.0.6 on 2022-09-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_stocktest_avg_volume_stocktest_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktest',
            name='avg_volume_float',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='book_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='bvps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='shares_float_float',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stocktest',
            name='short_float_float',
            field=models.FloatField(default=0),
        ),
    ]
