# Generated by Django 4.0.6 on 2022-09-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_stockinfo_id_remove_stocktest_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='industryinfo',
            name='name',
            field=models.TextField(default='default', primary_key=b'I01\n', serialize=False),
        ),
    ]
