# Generated by Django 4.0.6 on 2022-09-30 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_industryinfo_id_alter_industryinfo_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockTest',
        ),
    ]
