# Generated by Django 4.0.6 on 2022-09-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_stockinfo_avg_volume_float_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='book_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='bvps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='shares_float_float',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='short_float_float',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='avg_volume_float',
            field=models.FloatField(default=0),
        ),
    ]
