# Generated by Django 4.0.6 on 2022-09-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_stockinfo_book_value_stockinfo_bvps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='shares_float',
            field=models.TextField(default='default'),
        ),
    ]
