# Generated by Django 4.0.6 on 2022-09-30 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_stockinfo_shares_float'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndustryInfo',
        ),
    ]
