# Generated by Django 4.0.6 on 2022-09-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_delete_industryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='dates',
            field=models.JSONField(default=['']),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='prices',
            field=models.JSONField(default=['']),
        ),
    ]
