# Generated by Django 4.0.6 on 2022-09-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_stockinfo_dates_stockinfo_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='dates',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='prices',
            field=models.JSONField(default={}),
        ),
    ]
