# Generated by Django 4.0.6 on 2022-10-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_stockinfo_dates_alter_stockinfo_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronjobtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester', models.TextField(default='default')),
            ],
        ),
    ]
