# Generated by Django 4.0.6 on 2022-10-27 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_cronjobtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cronjobtest',
        ),
    ]
