# Generated by Django 4.0.6 on 2022-11-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_stockinfo_avg_eps_stockinfo_avg_fwdpe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='rev_growth_grade',
            field=models.TextField(default='default'),
        ),
    ]
