# Generated by Django 4.0.6 on 2022-11-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_stockinfo_rev_growth_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='profit_margin_grade',
            field=models.TextField(default='default'),
        ),
    ]
