# Generated by Django 4.0.6 on 2022-11-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_stockinfo_profit_margin_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='book_value',
            field=models.TextField(default=0),
        ),
    ]
