# Generated by Django 4.0.6 on 2022-11-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_stockinfo_book_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='overall_grade',
            field=models.FloatField(default=0),
        ),
    ]
