# Generated by Django 4.0.6 on 2022-11-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_stockinfo_overall_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='overall_grade_num',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='overall_grade',
            field=models.TextField(default='default'),
        ),
    ]
