# Generated by Django 4.0.6 on 2022-11-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_stockinfo_overall_grade_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestStocks',
            fields=[
                ('name', models.TextField(default='default', primary_key=b'I01\n', serialize=False)),
            ],
        ),
    ]
