# Generated by Django 4.0.6 on 2022-11-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_beststocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorstStocks',
            fields=[
                ('name', models.TextField(default='default', primary_key=b'I01\n', serialize=False)),
            ],
        ),
    ]
