# Generated by Django 4.0.6 on 2022-12-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_worststocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='last_update',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='stock_price',
            field=models.FloatField(default=0),
        ),
    ]
