# Creates objects in the Sqlite3 Daztabase
from pickle import TRUE
from django.db import models

class BestStocks(models.Model):
    name = models.TextField(default='default',primary_key=TRUE)

class WorstStocks(models.Model):
    name = models.TextField(default='default',primary_key=TRUE)

class StockInfo(models.Model):
    name = models.TextField(default='default',primary_key=TRUE)
    industry = models.TextField(default='default')
    sector = models.TextField(default='default')
    company_name = models.TextField(default='default')
    beta  = models.FloatField(default=69.69)
    pb = models.TextField(default='default')
    ps = models.TextField(default='default')
    pe = models.TextField(default='default')
    fwdpe = models.TextField(default='default')
    eps = models.TextField(default='default')
    pb_float = models.FloatField(default=69.69)
    ps_float =  models.FloatField(default=69.69)
    pe_float =  models.FloatField(default=69.69)
    fwdpe_float =  models.FloatField(default=69.69)
    eps_float =  models.FloatField(default=69.69)
    mkt_cap_short = models.TextField(default='default')
    mkt_cap = models.FloatField(default=69.69)
    revenue_short = models.TextField(default='default')
    revenue = models.FloatField(default=69.69)
    profit_short = models.TextField(default='default')
    profit = models.FloatField(default=69.69)
    profit_margin = models.TextField(default='default')
    profit_margin_float = models.FloatField(default=69.69)
    rev_growth = models.TextField(default='default')
    rev_growth_float = models.FloatField(default=69.69)
    avg_volume_float = models.FloatField(default=69.69)
    avg_volume = models.TextField(default='default')
    shares_float = models.TextField(default='default')
    short_float = models.TextField(default='default')
    book_value = models.TextField(default=0)
    bvps = models.FloatField(default=0)
    avg_volume_float = models.FloatField(default=0)
    shares_float_float = models.FloatField(default=0)
    short_float_float = models.FloatField(default=0)
    prices = models.JSONField(default=dict)
    dates = models.JSONField(default=dict)
    avg_pe = models.FloatField(default=69.69)
    avg_ps = models.FloatField(default=69.69)
    avg_pb = models.FloatField(default=69.69)
    avg_eps = models.FloatField(default=69.69)
    avg_fwdpe = models.FloatField(default=69.69)
    avg_mkt_cap = models.TextField(default='default')
    ind_size = models.TextField(default='default')
    profit_short = models.TextField(default='default')
    revenue_short = models.TextField(default='default')
    dtc = models.FloatField(default=69.69)
    mkt_share = models.TextField(default='default')
    mkt_share_float = models.FloatField(default=69.69)
    grade = models.TextField(default='default')
    rev_growth_grade = models.TextField(default='default')
    profit_grade = models.TextField(default='default')
    profit_margin_grade = models.TextField(default='default')
    pe_grade = models.TextField(default='default')
    ps_grade = models.TextField(default='default')
    pb_grade = models.TextField(default='default')
    eps_grade = models.TextField(default='default')
    fwdpe_grade = models.TextField(default='default')
    avg_rev = models.TextField(default='default')
    avg_rev_growth = models.TextField(default='default')
    avg_profit = models.TextField(default='default')
    avg_profit_margin = models.TextField(default='default')
    overall_grade_num = models.FloatField(default=0)
    overall_grade = models.TextField(default='default')
    stock_price = models.FloatField(default=0)
    last_update = models.TextField(default='default')


    def __str__(self):
        return self.name